http://www.tacketmusic.com/News/News.html

PERFORMING
STUDIO
EDUCATION
PRODUCTION COMPOSING

------

SPLASH

PERFORMANCE - LIVE DATES - INTRO BIO BLURB - PROJECTS ( RAE, JOHHNY SONIC, HAYLEY SALES, NIKKI D., SIDE ONE )
PRODUCTION - SPAGEHETTI FIRE PRODUCTIONS - TRACKS BY MAIL - SESSION WORK - ( MORE GEAR PICS LESS ROOM )
EDUCATION - digipen - link to profile - https://www.digipen.edu/academics/degree-programs/bamsd/

TRACKS BY MAIL

BIO

CONTACT